clear;
close all;
clc;
R = input("Enter your RollNo. :");
b = input("y-intercept :");
x = linspace(0, 10, 10);
y = R * x + b;
noise = randn(size(x));
y_noisy = y + noise;
figure;
plot(x, y_noisy, 'bo', 'MarkerSize', 8, 'LineWidth', 0.2);
hold on;
plot(x, y, 'r-', 'LineWidth', 0.2);
xlabel('X-axis');
ylabel('Y-axis');
title(['Data Points with Linear Fit Slope Close to R = ', num2str(R)]);
grid on;
hold off;
p1 = polyfit(x, y_noisy, 1);
p2 = polyfit(x, y_noisy, 2);
y_fit_linear = polyval(p1, x);
y_fit_quad = polyval(p2, x);
figure;
plot(x, y_noisy, 'bo', 'MarkerSize', 8, 'LineWidth', 0.2);
hold on;
plot(x, y_fit_linear, 'g-', 'LineWidth', 0.2);
plot(x, y_fit_quad, 'm--', 'LineWidth', 0.2);
xlabel('X-axis');
ylabel('Y-axis');
title('Polynomial Curve Fitting');
legend('Noisy Data', 'Linear Fit', 'Quadratic Fit', 'Location', 'best');
grid on;
hold off;